### ISSUE TITLE
netMHCpan doesn't seem to work on epitopepredict

### ISSUE THREAD

**Issue by christelvanharen** [dmnfarrell/epitopepredict#12]
Hi,

I would like to use epitopepredict for my predictions. Tepitope and mhcflurry work, but netMHCpan does not. I use the same test.config file for all of the mentioned predictors. However, netMHCpan does work when I don't use epitopepredict, see result. I don't understand what I'm doing wrong here.

test.config:
```
[base]
compression = 
cutoff_method = rank
cutoffs = 0.8
fasta_header_sep =  
mhc1_alleles = mhc1_supertypes
mhc1_length = 9
n = 1
names = 
overwrite = yes
path = results/test_original
predictors = netmhcpan
sequence_file = graduation_internship/data/output/test_e.fasta
threads = 1
verbose = no
```

test_e.fasta:
```
>epitope_28958
ITKKVADLVGF
>epitope_36773
LIYDSSLCDL
>epitope_20914
GLIEKNIEL
>epitope_18159
FVFLRNFSL
>epitope_17353
FPPSPLFFFL
>epitope_6671
CMTWNQMNL
>epitope_16970
FLWGPRALV
>epitope_23322
GYDQIMPKK
>epitope_75043
YMDGTMSQV
>epitope_19613
GFRLGFLHSGTAKSV

```
result:
```
(internship) cvharen@server:~$ epitopepredict -c test.conf -r
input is 10 protein sequences
netMHCpan appears to be installed
predictor: netmhcpan
alleles: HLA-A*01:01, HLA-A*02:01, HLA-A*03:01, HLA-A*24:02, HLA-B*07:02, HLA-B*44:03
length: 9
threads: 1
Traceback (most recent call last):
  File "/home/cvharen/anaconda3/envs/internship/bin/epitopepredict", line 33, in <module>
    sys.exit(load_entry_point('epitopepredict', 'console_scripts', 'epitopepredict')())
  File "/home/cvharen/src/epitopepredict/epitopepredict/app.py", line 491, in main
    W.run()
  File "/home/cvharen/src/epitopepredict/epitopepredict/app.py", line 136, in run
    P.predict_proteins(self.sequences, length=length, alleles=a, names=self.names,
  File "/home/cvharen/src/epitopepredict/epitopepredict/base.py", line 901, in predict_proteins
    results = self.predict_sequences(args, **kwargs)
  File "/home/cvharen/src/epitopepredict/epitopepredict/base.py", line 932, in predict_sequences
    results = self._predict_sequences(recs, alleles=alleles, path=path,
  File "/home/cvharen/src/epitopepredict/epitopepredict/base.py", line 1000, in _predict_sequences
    df = self.predict(peptides=peptides, sequence=seq, allele=a, name=name,
  File "/home/cvharen/src/epitopepredict/epitopepredict/base.py", line 1316, in predict
    res = self.read_result(temp)
  File "/home/cvharen/src/epitopepredict/epitopepredict/base.py", line 1255, in read_result
    res = pd.read_csv(io.BytesIO(temp), comment='#', names=cols, sep='\s+',
TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'
```

**Comment by dmnfarrell** [comment]
what version of netmhcpan are you using. 4.0 is supported. 4.1 seems to be the latest. it could be that newer versions have changed the output format.

**Comment by christelvanharen** [comment]
Hi, I am using version 4.1. What do you recommend?

**Comment by dmnfarrell** [comment]
Can you not try version 4.0 instead? https://services.healthtech.dtu.dk/services/NetMHCpan-4.0/
