### ISSUE TITLE
TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by wt12318** [dmnfarrell/epitopepredict#5]
Hi,
After I installed the tool, test it ,but some errors happened:

```
epitopepredict -n -t

wrote config file default.conf
Traceback (most recent call last):
  File "/public/slst/home/wutao2/miniconda3/bin/epitopepredict", line 8, in <module>
    sys.exit(main())
  File "/public/slst/home/wutao2/miniconda3/lib/python3.8/site-packages/epitopepredict/app.py", line 497, in main
    neo.test_run()
NameError: name 'neo' is not defined
```
Then I add `from epitopepredict import neo` to the file `app.py` and test it again, but this time one problem happened again:

```
epitopepredict -n -t

neoepitope workflow test
checking for ref human genome
INFO:pyensembl.download_cache:Fetching /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz from URL ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
INFO:datacache.download:Downloading ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz
INFO:pyensembl.download_cache:Fetching /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz from URL ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.75.cdna.all.fa.gz
INFO:datacache.download:Downloading ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.75.cdna.all.fa.gz to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz
INFO:pyensembl.download_cache:Fetching /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz from URL ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh37.75.ncrna.fa.gz
INFO:datacache.download:Downloading ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh37.75.ncrna.fa.gz to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz
INFO:pyensembl.download_cache:Fetching /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz from URL ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/pep/Homo_sapiens.GRCh37.75.pep.all.fa.gz
INFO:datacache.download:Downloading ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/pep/Homo_sapiens.GRCh37.75.pep.all.fa.gz to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz
INFO:pyensembl.database:Creating database: /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.db
INFO:pyensembl.database:Reading GTF from /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_name', 'gene_biotype', 'transcript_id', 'transcript_name', 'exon_number', 'exon_id', 'ccds_id', 'protein_id']
INFO:root:Using column 'source' to replace missing 'transcript_biotype'
INFO:datacache.database_helpers:Creating database /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.db containing: CDS, gene, transcript, stop_codon, exon, start_codon
INFO:datacache.database:Running sqlite query: "CREATE TABLE CDS (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 791856 rows into table CDS
INFO:datacache.database:Creating index on CDS (seqname, start, end)
INFO:datacache.database:Creating index on CDS (gene_name)
INFO:datacache.database:Creating index on CDS (gene_id)
INFO:datacache.database:Creating index on CDS (transcript_id)
INFO:datacache.database:Creating index on CDS (transcript_name)
INFO:datacache.database:Creating index on CDS (exon_id)
INFO:datacache.database:Creating index on CDS (protein_id)
INFO:datacache.database:Creating index on CDS (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE gene (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT UNIQUE PRIMARY KEY NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 63677 rows into table gene
INFO:datacache.database:Creating index on gene (seqname, start, end)
INFO:datacache.database:Creating index on gene (gene_name)
INFO:datacache.database:Creating index on gene (transcript_id)
INFO:datacache.database:Creating index on gene (transcript_name)
INFO:datacache.database:Creating index on gene (exon_id)
INFO:datacache.database:Creating index on gene (protein_id)
INFO:datacache.database:Creating index on gene (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE transcript (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT UNIQUE PRIMARY KEY NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 215170 rows into table transcript
INFO:datacache.database:Creating index on transcript (seqname, start, end)
INFO:datacache.database:Creating index on transcript (gene_name)
INFO:datacache.database:Creating index on transcript (gene_id)
INFO:datacache.database:Creating index on transcript (transcript_name)
INFO:datacache.database:Creating index on transcript (exon_id)
INFO:datacache.database:Creating index on transcript (protein_id)
INFO:datacache.database:Creating index on transcript (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE stop_codon (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 73411 rows into table stop_codon
INFO:datacache.database:Creating index on stop_codon (seqname, start, end)
INFO:datacache.database:Creating index on stop_codon (gene_name)
INFO:datacache.database:Creating index on stop_codon (gene_id)
INFO:datacache.database:Creating index on stop_codon (transcript_id)
INFO:datacache.database:Creating index on stop_codon (transcript_name)
INFO:datacache.database:Creating index on stop_codon (exon_id)
INFO:datacache.database:Creating index on stop_codon (protein_id)
INFO:datacache.database:Creating index on stop_codon (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE exon (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 1306656 rows into table exon
INFO:datacache.database:Creating index on exon (seqname, start, end)
INFO:datacache.database:Creating index on exon (gene_name)
INFO:datacache.database:Creating index on exon (gene_id)
INFO:datacache.database:Creating index on exon (transcript_id)
INFO:datacache.database:Creating index on exon (transcript_name)
INFO:datacache.database:Creating index on exon (exon_id)
INFO:datacache.database:Creating index on exon (protein_id)
INFO:datacache.database:Creating index on exon (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE start_codon (transcript_name TEXT NOT NULL, gene_name TEXT NOT NULL, transcript_biotype TEXT NOT NULL, seqname TEXT NOT NULL, protein_id TEXT NOT NULL, strand TEXT NOT NULL, ccds_id TEXT NOT NULL, exon_number TEXT NOT NULL, gene_biotype TEXT NOT NULL, transcript_id TEXT NOT NULL, end INT NOT NULL, start INT NOT NULL, gene_id TEXT NOT NULL, feature TEXT NOT NULL, exon_id TEXT NOT NULL, source TEXT NOT NULL)"
INFO:datacache.database:Inserting 73358 rows into table start_codon
INFO:datacache.database:Creating index on start_codon (seqname, start, end)
INFO:datacache.database:Creating index on start_codon (gene_name)
INFO:datacache.database:Creating index on start_codon (gene_id)
INFO:datacache.database:Creating index on start_codon (transcript_id)
INFO:datacache.database:Creating index on start_codon (transcript_name)
INFO:datacache.database:Creating index on start_codon (exon_id)
INFO:datacache.database:Creating index on start_codon (protein_id)
INFO:datacache.database:Creating index on start_codon (ccds_id)
INFO:datacache.database:Running sqlite query: "CREATE TABLE _datacache_metadata (version INT)"
INFO:datacache.database:Running sqlite query: "INSERT INTO _datacache_metadata VALUES (3)"
INFO:pyensembl.sequence_data:Parsing sequences from FASTA file at /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz
INFO:pyensembl.sequence_data:Saving sequence dictionary to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Parsing sequences from FASTA file at /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz
INFO:pyensembl.sequence_data:Saving sequence dictionary to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.ncrna.fa.gz.pickle
INFO:pyensembl.sequence_data:Parsing sequences from FASTA file at /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz
INFO:pyensembl.sequence_data:Saving sequence dictionary to /public/slst/home/wutao2/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle
pyensembl genome files cached in None
No module named 'varcode'
varcode required. please run pip install varcode
running neoepitope predictions
no such file p
no such file u
no such file b
no such file l
no such file i
no such file c
no such file s
no such file l
no such file s
no such file t
no such file h
no such file o
no such file m
no such file e
no such file w
no such file u
no such file t
no such file a
no such file o
no such file 2
no such file m
no such file i
no such file n
no such file i
no such file c
no such file o
no such file n
no such file d
no such file a
no such file 3
no such file l
no such file i
no such file b
no such file p
no such file y
no such file t
no such file h
no such file o
no such file n
no such file 3
no such file 8
no such file s
no such file i
no such file t
no such file e
no such file -
no such file p
no such file a
no such file c
no such file k
no such file a
no such file g
no such file e
no such file s
no such file e
no such file p
no such file i
no such file t
no such file o
no such file p
no such file e
no such file p
no such file r
no such file e
no such file d
no such file i
no such file c
no such file t
no such file t
no such file e
no such file s
no such file t
no such file i
no such file n
no such file g
no such file i
no such file n
no such file p
no such file u
no such file t
no such file v
no such file c
no such file f
Traceback (most recent call last):
  File "/public/slst/home/wutao2/miniconda3/bin/epitopepredict", line 8, in <module>
    sys.exit(main())
  File "/public/slst/home/wutao2/miniconda3/lib/python3.8/site-packages/epitopepredict/app.py", line 497, in main
    neo.test_run()
  File "/public/slst/home/wutao2/miniconda3/lib/python3.8/site-packages/epitopepredict/neo.py", line 813, in test_run
    W.run()
  File "/public/slst/home/wutao2/miniconda3/lib/python3.8/site-packages/epitopepredict/neo.py", line 99, in run
    if len(cutoffs) < len(preds) :
TypeError: object of type 'float' has no len()
```

What should I do to handle this error?

Thank you

**Comment by wt12318** [comment]
Problem solved by installing varcode and ncbi-blast.
Sorry for bothering
